INSERT INTO USER VALUES (HIBERNATE_SEQUENCE.NEXTVAL, SYSDATE(), 'hari1', 'role1');
INSERT INTO USER VALUES (HIBERNATE_SEQUENCE.NEXTVAL, SYSDATE(), 'hari2', 'role2');
INSERT INTO USER VALUES (HIBERNATE_SEQUENCE.NEXTVAL, SYSDATE(), 'hari3', 'role3');
INSERT INTO USER VALUES (HIBERNATE_SEQUENCE.NEXTVAL, SYSDATE(), 'hari4', 'role4');