INSERT INTO USER VALUES (USER_SEQ.NEXTVAL, SYSDATE(), 'hari1', 'role1');
INSERT INTO USER VALUES (USER_SEQ.NEXTVAL, SYSDATE(), 'hari2', 'role2');
INSERT INTO USER VALUES (USER_SEQ.NEXTVAL, SYSDATE(), 'hari3', 'role3');
INSERT INTO USER VALUES (USER_SEQ.NEXTVAL, SYSDATE(), 'hari4', 'role4');
INSERT INTO ADDRESS VALUES (ADDRESS_SEQ.NEXTVAL, 'Address11', 'Address12', 'city11', 'state11', 1);
INSERT INTO ADDRESS VALUES (ADDRESS_SEQ.NEXTVAL, 'Address12', 'Address12', 'city12', 'state12', 1);